name: Cadastrar Participante
description: Cadastro de Participantes
title: "[Participante]:"
body:
  - type: input
    id: nome
    attributes:
      label: Nome do Participante;
      description: Nome do Participante
      placeholder: ex. Harry Potter
    validations:
      required: true
  - type: input
    id: email
    attributes:
      label: Email;
      description: E-mail do participante
      placeholder: ex. harry.potter@hogwarts.com.uk
    validations:
      required: true
  - type: input
    id: gituser
    attributes:
      label: Usuário do GitHub;
      description: Nome de usuário da sua conta
      placeholder: ex. harrypotter
    validations:
      required: true
  - type: dropdown
    id: desafio
    attributes:
      label: Para qual desafio está se inscrevendo?
      multiple: true
      options:
        - desafio1
        - desafio2
        - desafio3
        - desafio4